### ISSUE TITLE
OTP text pasting support

### ISSUE THREAD

**Issue by vrajendraBhavsar** [Leeonardoo/OtpTextField-Compose#1]
Hii @Leeonardoo, Came across your library and it seems like a work of art. Super smooth animation is enabling a delightful experience. I have a question to ask, how can I enable text copying and pasting functionality? Like copying OTP from SMS and pasting it down to the OTP view and it'd paste in all the individual OTP texts into the individual Views if the length of an OTP is matching.

**Comment by Leeonardoo** [comment]
Hi, thank you 🙃! For copying I don't really see a way to do that the right way without some crazy workarounds or buggy selection. But for pasting, as I'm using just a single TextField if you remove the line that has `LocalTextToolbar provides EmptyTextToolbar` [right here](https://github.com/Leeonardoo/OtpTextField-Compose/blob/4e05a90705ef58579d6b0ef30185b3cf348ac6da/app/src/main/java/io/leeonardoo/otptextfield/OutlinedOtpTextField.kt#L83) the paste option should appear and just work. It should paste all digits up to the number set on the component
